# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [4]:
print(1+2)

3


* <b>Vector is one dimensional(1-D) array.<b> <br>
* <b>Matrix is two dimensional(2-D) array.<b>

**2. How to import `NumPy` library?** 

In [1]:
# To avoid overwriting the output, please code here
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [2]:
list_1 = [1,2,3,4,5]

In [3]:
# To avoid overwriting the output, please code here
arr = np.array(list_1)
arr, type(arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [6]:
# To avoid overwriting the output, please code here 
np.arange(6)

array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [7]:
# To avoid overwriting the output, please code here
np.zeros(5)

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [8]:
# To avoid overwriting the output, please code here
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [8]:
# To avoid overwriting the output, please code here 
print(np.ones(5))

[1. 1. 1. 1. 1.]


**8. Generate an array of "5" tens.**

In [9]:
# To avoid overwriting the output, please code here
np.ones(5)*10

array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [10]:
# To avoid overwriting the output, please code here
np.arange(52, 100, 2)

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [11]:
# To avoid overwriting the output, please code here
np.linspace(0, 1, 10, retstep = True)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [12]:
# To avoid overwriting the output, please code here
# Generating vector array
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
# To avoid overwriting the output, please code here
# reshape to convert into 2-d
x.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
# To avoid overwriting the output, please code here 

In [15]:
# Using shape

**12. Please generate the following matrix.**

In [16]:
# To avoid overwriting the output, please code here
y = np.linspace(0.1, 2.5, 25)
y.reshape(5, 5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [17]:
# To avoid overwriting the output, please code here
z = np.linspace(0, 24, 25, dtype = 'int32')
z.reshape(5, 5)  # if we use print() function, then output doesn't look like same

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [18]:
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

* <b>arange() takes 3rd argument as step size.<b><br>
* <b>linspace() take 3rd argument as no of point we want.<b>

**15. How to generate a single random integer number using NumPy built-in function?**

In [19]:
# To avoid overwriting the output, please code here
random_number = np.random.randint(0, 10)
print(random_number)

0


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [20]:
# To avoid overwriting the output, please code here
print(np.random.rand(7, 5))

[[5.92156339e-01 2.47617235e-01 5.91962266e-01 7.67569364e-01
  1.70806280e-01]
 [3.27798836e-01 7.87705997e-01 9.91819093e-02 4.70681821e-01
  6.07189805e-01]
 [8.68369587e-04 5.88265042e-01 3.06174896e-01 4.85491736e-01
  3.93920777e-01]
 [3.78383086e-01 6.20082731e-01 3.28591662e-01 9.68779358e-01
  7.07627707e-01]
 [9.61499394e-01 2.35574168e-01 8.34659407e-01 4.97886968e-01
  3.85116610e-02]
 [5.93777325e-01 8.11788741e-01 5.02730907e-01 6.37978501e-01
  2.89968792e-01]
 [6.63432573e-01 7.47623217e-02 9.49115834e-01 6.14956980e-02
  1.78470084e-01]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [21]:
# To avoid overwriting the output, please code here
np.eye(5)*5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 