In [1]:
import numpy as np

In [2]:
arr = np.array([2, 4, 5])
arr

array([2, 4, 5])

In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((4, 2), dtype="int32")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [6]:
np.full((5, 6), 99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [7]:
# random decimal number between 0 to 1 will be provided in the given shape
np.random.rand(4, 2)

array([[0.52858001, 0.2540364 ],
       [0.78485799, 0.26071383],
       [0.33847567, 0.88581047],
       [0.1833819 , 0.00741529]])

In [9]:
# random integer number (start, end, how many numbers we want[this is by default 1xn array])
# same int may repeat 
np.random.randint(1, 100, 10)

array([48, 27, 12, 68,  4, 80, 80, 42, 67, 55])

In [11]:
# we can also pass size of array/ matrix as the third parameter
np.random.randint(-4, 8, size=(3, 3))

array([[-4,  6,  4],
       [ 7,  7,  5],
       [-3, -1,  0]])

In [12]:
np.random.randn(20)

array([ 1.20240839,  0.39659943,  0.32964295,  0.35121197,  0.15482666,
       -1.38743566,  0.05668685, -0.29621909, -0.60897969,  0.34253144,
        1.10547984,  0.64803659,  0.10024002, -0.22788879,  0.57112087,
        0.02046146,  0.94785177, -1.05208925, -1.22306063,  1.3450526 ])

In [14]:
np.identity(5, dtype="int32")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
# short form of identity()
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])